export const languages = {
    "uz": {
        "my_tasks": "Mening vazifalarim",
        "home_title": "Telegramda loyihalarni boshqaring",
        "home_description": "Ishchi guruhlaringizga bot qo'shing va vazifalarni rejalashtiring",
        "add_project": "Loyiha qo'shish",
        "new_task": "Yangi vazifa",
        "task_name": "Vazifa nomi",
        "task_description": "Izoh",
        "deadline": "Deadline",
        "project": "Loyiha",
        "executor": "Ijrochi",
        "attach_a_file": "Faylni biriktirish",
        "create": "Yaratish",
        "created_at": "Yaratilgan sana",
        "author": "Muallif",
        "status": "Status",
        "comments": "Izohlar",
        "participant": "ishtirokchi",
        "select_all": "Barchasini tanlang",
        "no_task_yet": "Hali vazifa yo'q",
        "start_date": "Boshlanish sanasi",
        "file": "Fayl",
        "change": "o'zgartirish",
        "priority": "ustuvorlik"
    },
    "en": {
        "my_tasks": "My tasks",
        "home_title": "Manage projects in Telegram",
        "home_description": "Add a bot to your workgroups and schedule tasks",
        "add_project": "Add a project",
        "new_task": "New task",
        "task_name": "Task name",
        "task_description": "Description",
        "deadline": "Deadline",
        "project": "Project",
        "executor": "Executor",
        "attach_a_file": "Attach a file",
        "create": "Create",
        "created_at": "Date of creation",
        "author": "Author",
        "status": "Status",
        "comments": "Comments",
        "participant": "participant",
        "select_all": "Select all",
        "no_task_yet": "No task yet",
        "start_date": "Start date",
        "file": "File",
        "change": "change",
        "priority": "priority"
    },
    "ru": {
        "my_tasks": "Мои задачи",
        "home_title": "Управляйте проектами в Telegram",
        "home_description": "Добавляйте бота в свои рабочие группы и планируйте задачи",
        "add_project": "Добавить проект",
        "new_task": "Новая задача",
        "task_name": "Название задачи",
        "task_description": "Описание",
        "deadline": "Дедлайн",
        "project": "Проект",
        "executor": "Исполнитель",
        "attach_a_file": "Прикрепить файл",
        "create": "Создать",
        "created_at": "Дата создания",
        "author": "Автор",
        "status": "Статус",
        "comments": "Комментарии",
        "participant": "участника",
        "select_all": "Выбрать всех",
        "no_task_yet": "Пока нет задания",
        "start_date": "Дата начала",
        "file": "Файлы",
        "change": "менять",
        "priority": "приоритет"
    }
}